//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class purchase_order
    {
        public int PurchaseID { get; set; }
        public string product { get; set; }
        public int supplier { get; set; }
        public int Quantity { get; set; }
        public decimal OrderTotal { get; set; }
    
        public virtual product product1 { get; set; }
        public virtual supplier supplier1 { get; set; }
    }
}
