//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sales_order
    {
        public string SaleID { get; set; }
        public string product_id { get; set; }
        public int customer { get; set; }
        public int Quantity { get; set; }
        public decimal ItemTotal { get; set; }
    
        public virtual customer customer1 { get; set; }
        public virtual product product { get; set; }
    }
}
